apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
  namespace: flask-app-demo
spec:
  selector:
    matchLabels:
      app: redisdb
  replicas: 1
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
      - name: redisdb
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6380
