apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  namespace: flask-app-demo
spec:
  selector:
    matchLabels:
      app: storefront
  replicas: 1
  template:
    metadata:
      labels:
        app: storefront
    spec:
      containers:
      - name: storefront
        image: neosam01/storefront:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8383