apiVersion: apps/v1
kind: Deployment
metadata:
  name: storesfront
  namespace: flask-app-demo
spec:
  selector:
    matchLabels:
      app: storesfront
  replicas: 1
  template:
    metadata:
      labels:
        app: storesfront
    spec:
      containers:
      - name: storesfront
        image: neosam01/storesfront:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8282
