apiVersion: v1
kind: Service
metadata:
  name: redisdb-service
  namespace: flask-app-demo
  labels:
    app: redisdb
spec:
  type: ClusterIP
  ports:
  - port: 6380
    targetPort: 6380
  selector:
    app: redisdb
