apiVersion: v1
kind: Service
metadata:
  name: storesfront-service
  namespace: flask-app-demo
  labels:
    app: storesfront
spec:
  type: ClusterIP
  ports:
  - port: 8787
    targetPort: 8787
  selector:
    app: storesfront 
