apiVersion: v1
kind: Service
metadata:
  name: storefront-service
  namespace: flask-app-demo
  labels:
    app: storefront
spec:
  type: ClusterIP
  ports:
  - port: 8989
    targetPort: 8989
  selector:
    app: storefront 
