apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  namespace: flask-app-demo
spec:
  selector:
    matchLabels:
      app: productcatalog
  replicas: 1
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      serviceAccountName: secretsademo
      containers:
      - name: productcatalog
        image: neosam01/ffchaosfront:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
