apiVersion: v1
kind: Service
metadata:
  name: productcatalog-service
  namespace: flask-app-demo
  labels:
    app: productcatalog
spec:
  type: LoadBalancer
  ports:
  - port: 5100
    targetPort: 5100
  selector:
    app: productcatalog 
